apiVersion: v1
kind: Service
metadata:
  name: loan-credit-predict-service
spec:
  type: LoadBalancer
  selector:
    app: loan-credit-predict
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9990
